### PR TITLE
Return 404 in case tenant sub-domain is "_", which is invalid

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
> @atodorov Looks good. You can merge it

It's not ready and it doesn't work. As-is the code should generate a 500 ISE instead of 404. At least that's what happens for me downstream.

**Comment by atodorov** [comment]
Test is now failing as expected, https://github.com/django-tenants/django-tenants/actions/runs/3233415392/jobs/5295238700, 
```
FAIL: test_invalid_hostname_should_return_404 (django_tenants.tests.test_middleware.InvalidHostname)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/django-tenants/django-tenants/django_tenants/tests/test_middleware.py", line 24, in test_invalid_hostname_should_return_404
    self.assertIsInstance(response, HttpResponseNotFound)
AssertionError: <HttpResponseBadRequest status_code=400, "text/html; charset=utf-8"> is not an instance of <class 'django.http.response.HttpResponseNotFound'>
```

When hostname is not valid the response is `400 BadRequest`.

**Comment by atodorov** [comment]
After the last commit, which modifies `TenantMainMiddleware`, the newly added test is reporting PASS. This PR is now ready for review.

**Comment by atodorov** [comment]
@tomturner  do you mind publishing a new version to PyPI ?

**Comment by tomturner** [comment]
Done

**Pull request merged**
