### PR TITLE
call tenant_command programmatically using call_command without errors

### PR DESCRIPTION
**Pull request by jackkweyunga**
…g errors.

### CODE REVIEW

**Comment by jackkweyunga** [comment]
addressing issue I raised https://github.com/django-tenants/django-tenants/issues/891#issue-1580873815

**Comment by tomturner** [comment]
@jackkweyunga thanks

**Comment by jackkweyunga** [comment]
happy to contribute

**Comment by trentmurray** [comment]
Hey mate - thanks for this. When do you think a pypi update could be made?

**Pull request merged**
