### PR TITLE
Tests & patches for #831

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
FTR 
https://github.com/django-tenants/django-tenants/actions/runs/3077513472/jobs/4972431214 and 
https://github.com/django-tenants/django-tenants/actions/runs/3077513472/jobs/4972431786

successfully reproduce #831 which means the newly added test must be doing it's job.

**Comment by atodorov** [comment]
@tomturner this is ready for review. The commit log & patch itself should be self-explanatory - in case we're using identity columns we need to reset them based on the number of records copied from the source schema. See also #831 for more background. 

I've also tested it locally within my application and it works there as well. 

A new version on PyPI when you get to it would be highly appreciated!

**Comment by tomturner** [comment]
@atodorov I am happy do you want to merge this in yourself?

**Comment by atodorov** [comment]
> @atodorov I am happy do you want to merge this in yourself?

I would love to but I can't. Looks like permissions issue:

image

**Comment by tomturner** [comment]
@atodorov can you try again

**Pull request merged**
