### PR TITLE
Fix #663 - Fixed incompatibility of DatabaseSchemaIntrospection with django

### LINKED ISSUE #663: Postgres backend introspection seems to be out of date
I am trying to introspect tables in my schema but I am met with an error.  Comparing the latest postgres introspection in Django against circa the time when this file was last committed to django-tenants one can see the deviation.

Latest:
https://github.com/django/django/blob/main/django/db/backends/postgresql/introspection.py

~3 years ago.
https://github.com/django/django/blob/f3a98224e6dd5f8846008512f281e452dc3b1909/django/db/backends/postgresql/introspection.py

Executing
```py
cursor = connection.cursor()
descr = connection.introspection.get_table_description(cursor, table_name)
```
produces the error
```py
  File "/usr/local/lib/python3.8/site-packages/django_tenants/postgresql_backend/introspection.py", line 49, in <listcomp>
    return [FieldInfo(*((force_text(line[0]),) + line[1:6] +
TypeError: __new__() missing 1 required positional argument: 'collation'
```

### PR DESCRIPTION
**Pull request by adrienrusso**
This PR fixes issue #663.

Instead of duplicating the code of the `DatabaseSchemaIntrospection` methods, the schema search path can simply be set on the cursor.

This class was clearly out of date and some of its functions no longer exist in django.

### CODE REVIEW

**Comment by tomturner** [comment]
@adrienrusso Thanks I will have a look at some point

**Comment by adrienrusso** [comment]
@tomturner any update?

**Comment by tomturner** [comment]
@adrienrusso thank you for doing this. Sorry for the wait it took a bit a time for me to test hence the deley.

Notes to myself on how I tested it

        from django.db import connection
        from django.apps import apps
        tables = connection.introspection.table_names()
        seen_models = connection.introspection.installed_models(tables)
        for model in apps.get_models():
            print(model)

**Comment by adrienrusso** [comment]
Thanks for the review and the merge 👌

**Pull request merged**
