### PR TITLE
Fix: add --prune option for django 4.1 compatibility

### PR DESCRIPTION
**Pull request by auirarrazaval**
See #779

### CODE REVIEW

**Comment by tomturner** [comment]
I will only merge when 4.1 is out. Thanks

**Comment by atodorov** [comment]
@tomturner thanks for the new release. However I'm not seeing 3.4.4 on PyPI yet. Can you please push the packages to PyPI as well ?

**Comment by tomturner** [comment]
Done

**Comment by cclauss** [comment]
I have `django-tenants v3.4.8` installed but unfortunately, when upgrading to Django v4.1, I am still getting:
```
>       if options["prune"]:
E       

.venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py:188: KeyError
```
* Is there a way to verify `django-tenants.__version__` (or similar) at runtime?
* Are there other dependencies that might cause Django v4.1 to raise `KeyError: 'prune'`?
* Any other tips or tricks about how to avoid the KeyErrror when upgrading to Django v4.1?

% `pip list | grep tenant`
```
django-tenants            3.4.8
tenant-schemas-celery     2.0.0
```

**Pull request merged**
