### PR TITLE
psycopg3 fixes

### PR DESCRIPTION
**Pull request by hho6643**
I think this fixes issues #948, #949, and #950.

### CODE REVIEW

**Comment by diogosilva30** [comment]
Any update on this? I want to use this package in a new project, and this is blocking the development with psycopg3

**Comment by hho6643** [comment]
> Any update on this? I want to use this package in a new project, and this is blocking the development with psycopg3

Hi @diogosilva30, while we wait for Tom to look at this, any chance you could try the patch on your own and see if things work OK for you?

**Comment by tomturner** [comment]
Please can people try this patch it would really help me. I have not converted to use psycopg3 but would be willing to merge if enough people try this patch.

**Comment by sailingbonbini** [comment]
I would love to give this a try but can't seem to find a simple way to get this branch running in my docker environment ... couldn't find anything in the docs either. Is there a best practise to get a branch running in docker?

**Comment by sailingbonbini** [comment]
Okay, so I've run one test with 'django-tenants==3.5.0' in my requirements.txt, and I'm getting the same "maximum recursions" error. With 'django-tenants @ git+https://github.com/hho6643/django-tenants.git@hho6643-psycopg3_fixes' in my requirements.txt django starts without complaining. I'm still working through the installation of django-tenants so can't run a end-to-end test yet.

**Comment by hho6643** [comment]
@tomturner  any chance 2 testers (me & sailingbonbini) are good enough to get this merged?

**Comment by miyou995** [comment]
@tomturner Hi 
before this pull request i had the  RecursionError: maximum recursion depth exceeded in comparison here
packages/psycopg/connection.py", line 476, in _check_connection_ok
    if self.pgconn.status == OK:
       ^^^^^^^^^^^^^^^^^^^^^^^^

i tested the changes form the 340f137 pull on my local django-tenant installation  and it worked
after that i encoutred this error on creating new tenant 
** File "/mnt/c/Users/amd/Desktop/sellergate/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 531, in validate_no_broken_transaction
    raise TransactionManagementError(
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.**
and again after testing the solution from f2352ae pull,  i was able to run django tenant with psycopg 3 and django 4.2.5 like a charm 
but didn't try this on production yet 
hope to see this merged and pushed to pypi

**Comment by tomturner** [comment]
Can someone create me a dockerfile that psycopg3?

**Comment by diogosilva30** [comment]
I have tried the aforementioned patch and seems to be working without any issues

**Review by Azrael-git — APPROVED** [review]
Works for me

**Comment by tomturner** [comment]
Can someone update the dockerfile so it uses psycopg3?

**Comment by DavidHaas1** [comment]
> Can someone update the dockerfile so it uses psycopg3?

I updated the requirements.txt so it pulls psycopg3. It looks like if requirements.txt is updated, the dockerfile follows.  I don't actually have/use Dockerfiles (sorry) so, I think it works but ???

**Comment by tomturner** [comment]
Thanks @hho6643

**Pull request merged**
