### PR TITLE
Testing with django 3.1

### PR DESCRIPTION
**Pull request by atodorov**
@tomturner I've realized the original test matrix wasn't implemented very well, see comment in commit log.

### CODE REVIEW

**Comment by atodorov** [comment]
@tomturner 

the last commit didn't help solve the issue with pinning Django versions. What I'm seeing is:

```
Installed /home/runner/work/django-tenants/django-tenants
Processing dependencies for django-tenants==3.2.1
Searching for Django<3.2,>=2.1
Reading https://pypi.org/simple/Django/
Downloading https://files.pythonhosted.org/packages/01/a5/fb3dad18422fcd4241d18460a1fe17542bfdeadcf74e3861d1a2dfc9e459/Django-3.1.1-py3-none-any.whl#sha256=b5fbb818e751f660fa2d576d9f40c34a4c615c8b48dd383f5216e609f383371f
Best match: Django 3.1.1
Processing Django-3.1.1-py3-none-any.whl
Installing Django-3.1.1-py3-none-any.whl to /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages
writing requirements to /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/Django-3.1.1-py3.6.egg/EGG-INFO/requires.txt
Adding Django 3.1.1 to easy-install.pth file
```

So first pip installs the expected version of Django but then when `setup.py devel` is executed it looks like Django gets upgraded. Do you have any ideas how to prevent this ?

**Comment by atodorov** [comment]
@tomturner this PR wasn't quite ready yet, see the last comment. Now that it is merged but still not doing what it is expected to do please tell me if you are planning to work on a fix or if I should do it? And also if you have any hints wrt my previous question.

**Comment by tomturner** [comment]
It worked for me when I use a requirement file. Not sure how you are installing it.

**Comment by atodorov** [comment]
That's strange. My previous comments show something different but the test logs for the latest commit on master branch look good. Not sure if I was looking at old logs or something else. Sorry for the noise.

**Pull request merged**
