### PR TITLE
Tests & minor refactoring

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by tomturner** [comment]
@atodorov Good idea putting a test in I will let you fix the test

**Comment by atodorov** [comment]
@tomturner I am seeing only 1 error in CI ATM which doesn't seem to be related to this PR. However I want to see passing CI before we can merge. 

I will rebase once tests on master are working once again.

**Comment by tomturner** [comment]
@atodorov First sorry that my bad commit caused a problem. I should have done it in branch. The only problem left is an error with Python 3.8 that only happen 50% of the time as stated in #335.

**Comment by tomturner** [comment]
@atodorov I thought it was only domain names that you were stopping the underscores not schema name. I use underscores in my project.    schema name  tom_1234  points to a domain name of tom.mydomain.net. This check in will crash my app. I happy to stop underscores in the domain name however not in the schema name.  I am also happy to stop people having uppercase character in both domain names and schema names.

**Comment by atodorov** [comment]
> @atodorov I thought it was only domain names that you were stopping the underscores not schema name. I use underscores in my project. schema name tom_1234 points to a domain name of tom.mydomain.net. This check in will crash my app. I happy to stop underscores in the domain name however not in the schema name. I am also happy to stop people having uppercase character in both domain names and schema names.

From what I can see the path is match the domain, then get the tenant object and it's schema name.  So how do you create your tenants/domains ? 

In my app we create the tenants first then the domain name and the left-most sub-domain matches the schema_name. 

It looks like this is app specific but I don't see an obvious place like view/Form that deals with data validation where such check, only for domains, can be enforced or a function that can be reused by other apps. 

On my end I can solve it with a custom form validation function but others may hit the same issue.

**Comment by tomturner** [comment]
For my app the only internal member of staff create my tenants so we type the domain and schema name in. However I do see what you are trying to do so we could put a setting in to allow users to do what you are trying to do.

**Comment by atodorov** [comment]
@tomturner I've taken a step back on this PR. I've dropped the last commit which changes the schema name validation regex so you can merge the tests and the rest of the changes. 

I will examine more closely my own app and this about a different solution. So far I'm leaning towards documentation + maybe a helper function to validate domain names or convert schema_name to domain name. Will open a separate PR, probably later today.

**Comment by tomturner** [comment]
@atodorov do I close this or are you redo it.

**Comment by atodorov** [comment]
> @atodorov do I close this or are you redo it?

@tomturner from what I can tell this PR should be ready to merge. I see removal of 1 unused function, merger of 1 helper function in the function that uses it and tests. Previous comments indicate I've dropped changes which were debatable and unwanted and I don't see them in the diff. 

If there's anything left to do on my side let me know where exactly.

**Comment by atodorov** [comment]
@tomturner ping. Can you please review this PR ?

**Comment by tomturner** [comment]
@atodorov I will look this however I got to check it doesn't break my schema name.   Can you confirm that understores are allowed?

**Comment by atodorov** [comment]
> Can you confirm that understores are allowed?

Yes, the latest version of this PR doesn't change the original behavior, only removes unnecessary helper functions.

**Comment by tomturner** [comment]
@atodorov Thanks I will now merge

**Pull request merged**
